/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mikrotik.view.main;

import br.mikrotik.view.cgnat.Cgnat;
import java.awt.Dimension;
import javax.swing.JInternalFrame;

/**
 *
 * @author jackson
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Cgnat
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        Dimension dim = new Dimension(606, 527);
        
        Dimension max = new Dimension(610, 530);
        this.setMinimumSize(dim);
        this.setPreferredSize(dim);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        buttonCgnat = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setPreferredSize(new java.awt.Dimension(606, 527));
        main.setRequestFocusEnabled(false);

        javax.swing.GroupLayout mainLayout = new javax.swing.GroupLayout(main);
        main.setLayout(mainLayout);
        mainLayout.setHorizontalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 606, Short.MAX_VALUE)
        );
        mainLayout.setVerticalGroup(
            mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );

        buttonCgnat.setText("CgNat");
        buttonCgnat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonCgnatMouseClicked(evt);
            }
        });
        jMenuBar1.add(buttonCgnat);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCgnatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonCgnatMouseClicked
         
        if (cgnat == null || !cgnat.isDisplayable()) 
        {
            cgnat = new Cgnat();
            main.add(cgnat);
            this.openFrameInCenter(cgnat);
        }
        cgnat.toFront();
    }//GEN-LAST:event_buttonCgnatMouseClicked
    
    public void openFrameInCenter(JInternalFrame jif) 
    {
        //Obtém o tamanho do desktop        
        Dimension desktopSize = getSize();

        //Obtém o tamanho da janela interna a ser aberta no desktop
        Dimension jInternalFrameSize = jif.getSize();

        //Calcula o centro do desktop com base em seu tamanho e no tamanho
        //da janela a ser aberta no centro
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;

        //Configura a posição da janela calculada        
        jif.setLocation(width, height);

        //Solicita que a janela seja eixbida ao usuário
        jif.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private Cgnat cgnat = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu buttonCgnat;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane main;
    // End of variables declaration//GEN-END:variables
}
